name: Auto-PR from Development to Main

on:
  push:
    branches:
      - development

jobs:
  create-pull-request:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and Auto-merge Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main             # The branch you want to merge changes INTO
          head: development    # The branch you want to merge changes FROM (use 'branch' instead of 'head')
          title: 'Sync development into main'
          body: 'This PR was automatically created by GitHub Actions to merge dev changes into main.'
          commit-message: 'Update from development branch'
          auto-merge: true      # optional, if you want it to auto-merge upon success
          delete-branch: false   # Optional: whether to delete the branch after merging