name: Auto-PR from Development to Main

on:
  push:
    branches:
      - development

jobs:
  create-pull-request:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: development
          title: 'Merge development into main'
          body: 'This PR was automatically created by GitHub Actions to merge dev changes into main.'
          commit-message: 'Update from development branch'
          delete-branch: false

      - name: Enable Auto-merge
        run: |
          gh pr merge --auto --merge "${{ steps.create_pr.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}