name: Auto-merge Development to Main

# Trigger the workflow every time you push to the `development` branch
on:
  push:
    branches:
      - development


permissions:
  contents: write
  pull-requests: write


jobs:
  merge-branch:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "vasilogi"
          git config user.email "jean.vasil@gmail.com"
          
      - name: Merge development into main
        run: |
          git checkout main
          git merge development
          git push origin main
