name: Auto PR and Merge

on:
  push:
    branches:
      - development

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches
          ref: development  # Explicitly checkout development branch

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
          base: main
          delete-branch: false
          title: 'Automated PR: Development to Main'
          body: |
            Automated PR created from development branch.
            
            Changes pushed to development branch will be merged into main.
          labels: automated-pr
          
      - name: Enable Pull Request Automerge
        if: steps.create-pr.outputs.pull-request-number
        run: |
          gh pr merge --auto --merge "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
