name: Create Pull Request
on:
  push:
    branches:
      - development

jobs:
  create-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build site
        run: npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update from development branch
          title: 'Merge development into main'
          body: |
            Automated PR to merge development changes into main branch
            
            Please review the changes before merging
          branch: development
          base: main
          delete-branch: false
